### ISSUE TITLE
User Logo is not shown after upload

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#10]
The src attribute of the <img element has alway the same, wrong value. Uploading another picture does not change the src attribute.

![image](https://cloud.githubusercontent.com/assets/18029124/23024992/a4803b48-f45c-11e6-9c3a-224d4b2afa90.png)

**Comment by silop4all** [comment]
@Markus-Becker  It has fixed by the commit d6d0f7ad943145be689e91be4e801b30f0b68549.

**Comment by Markus-Becker** [comment]
It does not work!

**Comment by Markus-Becker** [comment]
Dupplicate of #5
