### ISSUE TITLE
The search does not work

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#11]
If I enter a search term and then press enter or click on the search button nothing happens. It doesn't seem that the browser does anything.

![image](https://cloud.githubusercontent.com/assets/18029124/23025166/3c108012-f45d-11e6-9e77-3a4777bc5bff.png)

**Comment by silop4all** [comment]
@Markus-Becker   At the moment, the html form is there (the search button is disabled) but none call is performed in the controllers. This functionality will be included in the next release.

**Comment by silop4all** [comment]
Search via keywords is supported. User enters terms and platform returns services and articles that meets the user input in case of customized search engine usage. The chars `,;|` and space are used as delimiters.

Check commit https://github.com/silop4all/aod/commit/f6a266b2bf5c51bd7236e81ff9f74972babd413b

Also, the Information division in search criteria area has removed and the Help term has renamed in FAQ term (https://github.com/silop4all/aod/commit/857bab07252ef2a27b1ca4ee0c939c7c42e4be47)

**Comment by Markus-Becker** [comment]
MB: Search tested and works
