### ISSUE TITLE
Description Text Area: To less characters

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#14]
When I create a new service I cannot enter our whole text into the Description Field because it is limited to only 500 characters. This is to less because most of our texts are longer.
![image](https://cloud.githubusercontent.com/assets/18029124/23164577/156ff08a-f838-11e6-8b9d-49bd93de04c2.png)

**Comment by silop4all** [comment]
@Markus-Becker I have increased its length at 4000 characters.

Check commit ba494b0e4628d022dbcd79254759890574433034.

**Comment by Markus-Becker** [comment]
It works!
