### ISSUE TITLE
Question: Where can I disable the Location Contraints fields for all views?

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#15]
We want to hide the Locational constraints. Which files do I have to edit?
![image](https://cloud.githubusercontent.com/assets/18029124/23164675/a4d1f2aa-f838-11e6-8ef1-6647dc1e9e29.png)

**Comment by silop4all** [comment]
@Markus-Becker This division is hidden if there are no locational constraints for the service. 

Check the commit 91ae60765299d287321f9a866740d57568654622

**Comment by Markus-Becker** [comment]
It works!
