### ISSUE TITLE
Question: How can we hide the "Ask a volunteer?" and "Ask a professional?" content

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#16]
We want to hide the content for "Ask a volunteer?" and "Ask a professional?". How can we do that?

![image](https://cloud.githubusercontent.com/assets/18029124/23164795/3c4cfc4c-f839-11e6-956f-b1aebfd8514f.png)

**Comment by silop4all** [comment]
@Markus-Becker You can do it by editing the  lines https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/app/templates/app/prosumers/search/services/preview.html#L457 and https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/app/templates/app/prosumers/search/services/preview.html#L471.

In particular, in both cases you could replace the `<div class="clearfix margin-bottom-25">` with `<div class="clearfix margin-bottom-25 hidden">`

**Comment by Markus-Becker** [comment]
added hidden class to hide content
