### ISSUE TITLE
Questions: How can we hide the "E-Mail contact" and "Telephone support" content

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#17]
We want to hide the "E-Mail contact" and "Telephone support" content. How can we do that?

![image](https://cloud.githubusercontent.com/assets/18029124/23164974/288ef2fe-f83a-11e6-8d9b-b01849c9bdf4.png)

**Comment by silop4all** [comment]
@Markus-Becker You can hide this content by editing the https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/app/templates/app/prosumers/search/services/preview.html#L485.

You could replace the `{% if customization_process %}` with the `{% if false %}` or `<div class="clearfix margin-bottom-25">` with `<div class="clearfix margin-bottom-25 hidden">`.

**Comment by Markus-Becker** [comment]
added hidden class to hide these entries
