### ISSUE TITLE
Bug: Relative Articles: Text overlaps border of tile

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#18]
The text of the "Relative Articles" protudes the border at the bottom of the tile.

![image](https://cloud.githubusercontent.com/assets/18029124/23210286/2f681060-f8fd-11e6-8e40-7dd697d4acf4.png)

**Comment by silop4all** [comment]
@Markus-Becker  I increased the min-/max-height of the box, filtered the length of the article's content and changed the html header of its title (h4->h5). 

Check the commit e6749a0e5d57028a57f43b1a8e3817b9180203fc

**Comment by Markus-Becker** [comment]
MB: Works!
