### ISSUE TITLE
Adaption: How can we hide calendar and notifications

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#20]
How can we hide the "calendar" and "my notifications" entries in the "my account" menu?

![image](https://cloud.githubusercontent.com/assets/18029124/23269246/3b4c27b0-f9f0-11e6-9e6c-356c133a0c96.png)

**Comment by silop4all** [comment]
@Markus-Becker You could comment the li elements in https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/app/templates/app/navbar-users.html  (lines 65-75)

**Comment by Markus-Becker** [comment]
It works!
