### ISSUE TITLE
Feature:Can you put the three video links together into one video link?

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#22]
This has more benefits:
  The user doesnt really care from which source the video comes from, so why should he always be forced to select all three options to find all videos?

  We will never put a video from vimeo or other sources into the system, so when you use only the vimeo option you will get an ugly "result not found" page.

  At the same time, as we will never add theses videos, the user will always press these buttons for nothing.

![threevideolinks](https://cloud.githubusercontent.com/assets/10863179/23404184/ed5f88ae-fdb3-11e6-84ee-5928f334d424.jpg)

**Comment by silop4all** [comment]
Done. Check commit https://github.com/silop4all/aod/commit/4756fca83c2a070f2c1827096e55252773c40bb1

**Comment by Markus-Becker** [comment]
MB: Tested -> works
