### ISSUE TITLE
Bug: What would/should the "Try different" button do?

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#23]
Just now pressing this button doesn't do anything.

![trydifferentbutton](https://cloud.githubusercontent.com/assets/10863179/23404538/cfaceaca-fdb5-11e6-8959-c27b514783df.jpg)

**Comment by silop4all** [comment]
@LifetoolAD The "Try different" feature is something like a simplified recommendation engine. It will consider what the user is looking for and will suggest other services that probably meet better the user needs. This feature is under development (it will be part of the app components).
