### ISSUE TITLE
Bug: The "Get the service!" button is always grayed out

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#24]
This button never gets active.
We will never sale anything so the easiest solution is to hide the button.

![gettheservicebutton](https://cloud.githubusercontent.com/assets/10863179/23404665/67397ae8-fdb6-11e6-9032-7c9d5221756b.jpg)

**Comment by silop4all** [comment]
@LifetoolAD The integration with Payment component is pending. Therefore, this button has disabled.
