### ISSUE TITLE
Bug: The title string of the service is changed in the overview and when the item is viewed

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#25]
My product is called "KlickTool Literacy AAC"
When viewed in the Overview the whole strings is in capitals: KLICKTOOL LITERACY AAC
When I open this product the title is: Klicktool Literacy Aac
When I want to edit this service the title is written in the right way: KlickTool Literacy AAC

![titlestringchanged](https://cloud.githubusercontent.com/assets/10863179/23405037/799a0250-fdb8-11e6-8321-e037d934ef27.jpg)

**Comment by silop4all** [comment]
@Markus-Becker I perform some Django (Jinja template engine) filters (title, capfirst etc) on the title of services in the templates. That's why the same title is presented with different way. I will use the same filter in all cases and I let you know.

**Comment by silop4all** [comment]
The title of services is displayed without tags. Check commit https://github.com/silop4all/aod/commit/0b610db78a9d9328c1b6582748b744f0041a0cc4

**Comment by Markus-Becker** [comment]
MB: tested -> works
