### ISSUE TITLE
Feature: Can the whole product field in the main page be clickable?

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#27]
There is only one button in every product so every click on the product could just open the product.
The big benefit here is that it doesn't matter anymore if the "get it" button is now covered by any controls,
as a click on a covered "get it" button will also click on the product and open it.

![getitcoveredagain](https://cloud.githubusercontent.com/assets/10863179/23405693/c10bd26e-fdbb-11e6-9f1c-727454fd5f7e.jpg)

**Comment by silop4all** [comment]
@LifetoolAD I have changed the width for small devices from col-sm-4 to col-sm-6 to avoid text wrap in the commit https://github.com/silop4all/aod/commit/a4ccddecc4b4e139acc60d5f1f53a9b72828a1ef. Could you check it?

**Comment by Markus-Becker** [comment]
@silop4all: It still does not fit for resolutions with a width of 992px up to 1199px:

![image](https://cloud.githubusercontent.com/assets/18029124/23950534/991e0412-098b-11e7-94b1-9265fd0aa115.png)

**Comment by silop4all** [comment]
I did the title of the services linkable. 

In medium devices, the layout is adjusted. Please check the commit https://github.com/silop4all/aod/commit/623c768322f6a8ab64e3db6b3706551b4f231d4b

**Comment by Markus-Becker** [comment]
MB: tested -> works
