### ISSUE TITLE
Is Ubuntu LTS 16.04 supported

### ISSUE THREAD

**Issue by SteveALee** [silop4all/aod#28]
The read me only mentions 14 but the P4A deliverable mentioned 16.

I'm using Desktop LTS 16.0.4

**Comment by silop4all** [comment]
@SteveALee Yes, AoD can be deployed in ubuntu 16.04. You need to cross check the python version; it is recommended to use python 2.7.x.

**Comment by SteveALee** [comment]
it's 2.7.12 so OK
