### ISSUE TITLE
Installation instructions specify git twice

### ISSUE THREAD

**Issue by SteveALee** [silop4all/aod#29]
```sh
sudo apt-get install git
```
appears twice

Incidentally, the following is easier to copy and paste, especially as '$' is always given
```sh
sudo apt-get install python-pip git unzip vim
```

**Comment by silop4all** [comment]
@SteveALee Thank you for the feedback. It has fixed in https://github.com/silop4all/aod/commit/f0decc2486ff960ad1adf80823b86857ec171135
