### ISSUE TITLE
Bug: User Logo is not shown in the Products View

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#32]
After I added a user logo I expected to see it on every product page that the user offers. But that's not the case:

![image](https://cloud.githubusercontent.com/assets/18029124/23955548/8205af46-099a-11e7-877d-495f6496343f.png)

**Comment by silop4all** [comment]
If the user has not uploaded any logo, a specific (font awesome) icon is displayed. Otherwise, the logo of user is displayed. Check here https://github.com/silop4all/aod/commit/3537cdad9b116b535c2ede8acfa3aaf2725eea52

**Comment by Markus-Becker** [comment]
MB: tested -> works
