### ISSUE TITLE
Change the caption of page 4 of the product / service editor

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#35]
At the moment it is "Lingual and locational constraints" but as I commented out the locational constraints I need to change it. I hope I can do it with rosetta when it will work.

**Comment by silop4all** [comment]
You can modify the title of the 4th tab in the template https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/app/templates/app/prosumers/provider-dashboard/services/registration/constraints.html#L7

**Comment by Markus-Becker** [comment]
MB: tested -> works
