### ISSUE TITLE
Requirement Steve Schuerz: We want to change the entries for type from "Human based" to "iOS" ...

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#37]
For our LIFEtool AoD implementation we need to change the types "human based" and "machine based" to these types: "iOS", "Android", "Win". How can we do this. Which files must we change?
![grafik](https://cloud.githubusercontent.com/assets/18029124/24802353/f6099186-1ba7-11e7-92da-0a8ca2e6cac3.png)

**Comment by silop4all** [comment]
Check the commit https://github.com/silop4all/aod/commit/4b271a33b9fb0e7b501e0ae8b0e60804318a0301.

For the existing services, you could update their types via the app_services.type. Available values are:
- I => iOS
- W => Windows
- A => Android
- H => Human
- M => Machine
- C => Community

**Comment by Markus-Becker** [comment]
MB: Tested -> works
