### ISSUE TITLE
Requirement: Remove Shopping Cart from GetIt Button

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#38]
Stefan wants that the shopping cart is removed from the GetIt... Button 
![grafik](https://cloud.githubusercontent.com/assets/18029124/25186323/222284b8-2520-11e7-9b06-0e7d33348207.png)

**Comment by silop4all** [comment]
Modified. Check commit https://github.com/silop4all/aod/commit/c86f129c6538a26b4f4fd546867ead1d5b9754f6

**Comment by Markus-Becker** [comment]
MB: Tested and it works
