### ISSUE TITLE
Requirement: "Get the service" should link to an external download site

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#39]
Stefan wants that the download link links to an external Download Provider who sells our software. It should be possible to link to an special product page and not to a general landing page!

![grafik](https://cloud.githubusercontent.com/assets/18029124/25186489/98324012-2520-11e7-9f6f-5ed7a863bb11.png)

**Comment by silop4all** [comment]
The commit https://github.com/silop4all/aod/commit/9b587237b06a842b65d5e23f8a3404d330244a90 solves this issue. MIgration in the data model is required.

**Comment by Markus-Becker** [comment]
fixed
