### ISSUE TITLE
Log In doesnt accept e-mail adress

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#4]
When you want to log in the text in the field says: "Username or Email"
Entering Email doesnt work here.
The easiest solution will be to change the text to only Username.

**Comment by silop4all** [comment]
The placeholder in the login template has updated. User authentication is performed via the username.
Check a87e286715e19032556c962503fabe3062d0f706.

**Comment by Markus-Becker** [comment]
Fixed!
