### ISSUE TITLE
Requirement: Increase the distance between checkbox and label

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#42]
![grafik](https://cloud.githubusercontent.com/assets/18029124/25386077/5d719072-29c6-11e7-9ca7-45702e94d447.png)

**Comment by silop4all** [comment]
Check commit https://github.com/silop4all/aod/commit/59d5ed36a18a96f0d765d1ee14c5949efe8f8f01. 

Then, go to /your-path-to-project/AssistanceOnDemand/ and type:
$ sudo -i
$ python manage.py collectstatic --noinput
$ chown -R www-data:www-data static/
$ service apache2 reload

**Comment by Markus-Becker** [comment]
is fixed
