### ISSUE TITLE
The "my collection" menu point will always lead to an empty page

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#45]
![image](https://cloud.githubusercontent.com/assets/10863179/25427390/b7b2ed9a-2a72-11e7-8bb6-8e58f10cd4d7.png)

In our project you can never buy a service so this will never populated.
The easy solution is to set this menu point invisible.

**Comment by silop4all** [comment]
You can hide this list item by adding the class="hidden" in the html element of the line https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/app/templates/app/navbar-users.html#L42.
