### ISSUE TITLE
Text: the word "service" is missing in the grey text

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#51]
![image](https://user-images.githubusercontent.com/10863179/30542346-59b33b76-9c7f-11e7-939e-e848daf10c16.png)

The Mouse over hinttext has the word "service", the grey text inside the box says: "Enter keywords related to your using the space character among them". Here after your should be the word "service".

**Comment by Markus-Becker** [comment]
Fixed: inserted "product" as this is the term we use.
