### ISSUE TITLE
After you purchase a free service the next small windows does not really show the "No" button

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#53]
![image](https://user-images.githubusercontent.com/10863179/30543577-f7e1a50e-9c83-11e7-8d92-bdaa59a8ae16.png)

The "No" button is there and you can click it, but we definitly encourage the user to press the "Yes" button.

**Comment by Markus-Becker** [comment]
fixed!
Changed color value#f7f7f7 to #f0ad4e for classes .btn-warning and so on in files
/opt/prosperity/AssistanceOnDemand/app/static/app/content/themes/bootstrap-facebook-square-skin.css and
/opt/prosperity/AssistanceOnDemand/app/static/app/content/bootstrap-facebook-square-skin.css
