### ISSUE TITLE
Write your review brings a "float division by zero" error

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#54]
![image](https://user-images.githubusercontent.com/10863179/30543832-c283c35a-9c84-11e7-881a-bf8643f9e72a.png)

This error was shown after I pressed the Submit button.

**Comment by silop4all** [comment]
@LifetoolAD  Is the database updated? Is there the table `app_evaluation_metrics` and its entries as mentioned in https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/sql/aod_data.sql#L190?

**Comment by Markus-Becker** [comment]
The problem was an empty table (app_evaluation_metrics) which was fixed by adding the correct values (line 190 to the end of file
https://github.com/silop4all/aod/blob/master/AssistanceOnDemand/sql/aod_data.sql)
