### ISSUE TITLE
Access the resources always opens "http://aod.lifetool.at/media/app/users/logos/1.jpg"

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#55]
When you open a product page of a product you have in your collection you can click the "Access the resources" button.
![image](https://user-images.githubusercontent.com/10863179/30631167-9e4a5d7c-9de3-11e7-9140-9967f0ba6117.png)

In the three products I have in my collection  every time the picture of the KlickTool cat is opened.
![image](https://user-images.githubusercontent.com/10863179/30631212-c22c6398-9de3-11e7-8849-ab6b8218d0aa.png)

**Comment by Markus-Becker** [comment]
This is hard coded in \app\templates\app\prosumers\search\services\preview.html, line 428

**Comment by silop4all** [comment]
@Markus-Becker  You have right. I'm working on it. 

By clicking the `Access the resources` button, the customer's browser will be redirected to an external link or a file will be downloaded (issue #39). It depends on what the provider enters in each service/product.

**Comment by silop4all** [comment]
The commit https://github.com/silop4all/aod/commit/9b587237b06a842b65d5e23f8a3404d330244a90 solves this issue. MIgration in the data model is required.

**Comment by Markus-Becker** [comment]
fixed
