### ISSUE TITLE
How can a user that registers a service provide Downloads and Materials?

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#7]
There is a section called "Links, downloads and materials".
How/where can i fill this with data?

![linksdownloadsandmaterials](https://cloud.githubusercontent.com/assets/10863179/22642880/b76f60ce-ec5c-11e6-854c-7650dbb81804.jpg)

**Comment by silop4all** [comment]
@LifetoolAD   After success authentication, go to the My account > My offering (from top menu) and under the box called "Services overview" you need to access the "Technical support" link per registered service/product. Each owner is able to add materials for the services that own.
