### ISSUE TITLE
Links in "Relative Articles" on main page protudes the borders of the tile

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#9]
![image](https://cloud.githubusercontent.com/assets/18029124/23024083/ccead29a-f458-11e6-8ec4-abb80518a960.png)

**Comment by silop4all** [comment]
@Markus-Becker Check the commit 9c4de2693e2f8bd79a6fc430e7dbff392a850c09. Fix images to be responsive and limit the title of the links. Check if it works.

**Comment by Markus-Becker** [comment]
Code from commit https://github.com/silop4all/aod/commit/9c4de2693e2f8bd79a6fc430e7dbff392a850c09
did not work. I changed lines 381 to 386 by this and it worked:

                        // keep link name if length is small. otherwise add static title
381                         $("#articles-result-multidata a").each(function(){
382                                 if ($(this).text().length > 25){
383                                         $(this).text(gettext('Follow link'));
384                                         //$(this).addClass('btn btn-sm btn-link');
385                                 }
386                         })

**Comment by Markus-Becker** [comment]
In the new AoD version was this bug again. The solution changed because the code changed:
same file line 598 has to be changed.
Old:
                            var updTitle = (title[title.length-1] > 25) ? gettext('Follow link'): title[title.length-1];

New:
                            var updTitle = (title[title.length-1].length > 25) ? gettext('Follow link'): title[title.length-1];
